# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b397b5d86332527cb93d31ef368adcb047554df05560240473a1c2e3254e55c755fd2ec0a272a8f28e04fd932e12d8d3ee7a47340b53b956198646b3ea0430d

test:
  secret_key_base: db5a85fb90cf7ed1f827a21d5086649e4af25cbf9fadd451319e5f51704c33a26484c08ce71270b624f2ec238287bd019c42ec4e5b188edd7ebd795e4f2bdcc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
